// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzW0VuVMytSboNu1jjHVEwOYjTAd8zr2Y',
    appId: '1:998311902174:web:2cbb7e1096e227a9aefb4f',
    messagingSenderId: '998311902174',
    projectId: 'raven-companion',
    authDomain: 'raven-companion.firebaseapp.com',
    storageBucket: 'raven-companion.appspot.com',
    measurementId: 'G-TV6ZZC031W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwmr6__hPNFbO-ROFj5IiNlvRj24qxQCE',
    appId: '1:998311902174:android:2fd2cdb882815b64aefb4f',
    messagingSenderId: '998311902174',
    projectId: 'raven-companion',
    storageBucket: 'raven-companion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn6tTpeukAtm2_1-aPwNzS5isrUk-RNtI',
    appId: '1:998311902174:ios:d8a4f42c643bd81caefb4f',
    messagingSenderId: '998311902174',
    projectId: 'raven-companion',
    storageBucket: 'raven-companion.appspot.com',
    iosClientId: '998311902174-9sebtllp6a2u66cgi1sgt81fhu9kpodj.apps.googleusercontent.com',
    iosBundleId: 'com.masterminds.raven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn6tTpeukAtm2_1-aPwNzS5isrUk-RNtI',
    appId: '1:998311902174:ios:d8a4f42c643bd81caefb4f',
    messagingSenderId: '998311902174',
    projectId: 'raven-companion',
    storageBucket: 'raven-companion.appspot.com',
    iosClientId: '998311902174-9sebtllp6a2u66cgi1sgt81fhu9kpodj.apps.googleusercontent.com',
    iosBundleId: 'com.masterminds.raven',
  );
}
